### ISSUE TITLE
Introducing Domain-Oriented Microservice Architecture

### ISSUE THREAD

**Issue by nowakprojects** [nowakprojects/SelfImprovement#3651]
https://eng.uber.com/microservice-architecture/

**Comment by MateuszNaKodach** [comment]
In other words, organizations adopt microservices for an operational benefit at the expense of performance. Organizations also must take on the cost to maintain the infrastructure necessary to support microservices. In many situations, it turns out, this trade-off makes a lot of sense, **but it is also a strong argument against a premature adoption of a microservice architecture.**

**Comment by MateuszNaKodach** [comment]
In other words, as Uber grew from 10s to 100s of engineers with multiple teams owning pieces of the tech stack, the monolithic architecture tied the fate of teams together and made it difficult to operate independently.

As a result, we adopted a microservice architecture. Ultimately our systems became more flexible, which allowed teams to be more autonomous.

**Comment by MateuszNaKodach** [comment]
DOMA intends to transform microservice architectures from something complex to something comprehensible: a structured set of flexible, reusable, and layered components.

**Comment by MateuszNaKodach** [comment]
**For instance, our map search services constitute a domain, fare services are a domain, matching platform (matching riders and drivers) are a domain.**

**Comment by MateuszNaKodach** [comment]
One can think of the top layers as specific user experiences (such as mobile features), and the bottom layers as generalized business functionality (such as account management or marketplace trips).

**Comment by MateuszNaKodach** [comment]
**many of Uber’s core business platforms started as rider or driver specific functionality that became more generalized as we developed more lines of business and they took on more dependencies (such as Uber Eats or Uber Freight).**
